language: python
dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip install ."

# get the test images
before_script:
  - "wget https://github.com/ianare/exif-samples/archive/master.tar.gz"
  - "tar -xzf master.tar.gz"

# could be much improved ...
script:
  - "find exif-samples-master -name *.tiff -o -name *.jpg | xargs EXIF.py"
  - "find exif-samples-master -name *.tiff -o -name *.jpg | xargs EXIF.py -dc"
